# Generated by Django 5.0.1 on 2025-03-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_propriedade_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='area_privativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='modalidade_venda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='valor_avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
