# Generated by Django 5.0.1 on 2025-03-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0003_propriedade_area_privativa_propriedade_area_terreno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='tipo_imovel',
            field=models.CharField(blank=True, help_text='Tipo extraído da descrição (Casa, Apartamento, Terreno, etc)', max_length=50, null=True),
        ),
    ]
