# Generated by Django 5.0.1 on 2025-03-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0004_propriedade_tipo_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude do imóvel', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude do imóvel', max_digits=9, null=True),
        ),
    ]
