# Generated by Django 5.0.1 on 2025-03-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0006_propriedade_imagem_url'),
    ]

    operations = [
    ]
