# Generated by Django 5.0.1 on 2025-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0006_propriedade_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='matricula_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Matrícula'),
        ),
    ]
