# Generated by Django 5.0.1 on 2025-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0007_add_analise_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='imagem_cloudinary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='imagem_cloudinary_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='tipo_imovel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
